-- CPA English Trainer — Supabase schema
-- Project: apefwcrsizqxpxhmsxmy (đã áp dụng trước đó — script này AN TOÀN để chạy lại,
-- không xoá bảng, không xoá dữ liệu; chỉ tạo mới nếu thiếu / thay policy bằng bản đúng).
--
-- SỬA SO VỚI BẢN TRƯỚC: bản trước bật row level security (enable row level security)
-- trên cả 5 bảng nhưng KHÔNG kèm policy nào. Với Postgres/Supabase, bật RLS mà không có
-- policy nghĩa là MỌI truy cập đều bị từ chối — kể cả chính chủ user qua publishable key.
-- Vậy nên khối "RLS POLICIES" bên dưới là phần bắt buộc phải chạy để app dùng được.

create table if not exists public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.study_progress (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  item_key text not null,
  item_type text not null check (item_type in ('word','family','collocation','question')),
  topic text,
  status text not null default 'new' check (status in ('new','learning','review','mastered')),
  ease_factor numeric(4,2) not null default 2.50,
  interval_days integer not null default 0,
  repetitions integer not null default 0,
  lapses integer not null default 0,
  due_at timestamptz not null default now(),
  last_reviewed_at timestamptz,
  correct_count integer not null default 0,
  wrong_count integer not null default 0,
  total_time_seconds integer not null default 0,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(user_id, item_key, item_type)
);

create table if not exists public.study_sessions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  mode text not null check (mode in ('vocabulary','word_family','collocation','cloze','mock_exam','review','word_formation','sentence_transform','translation')),
  started_at timestamptz not null default now(),
  ended_at timestamptz,
  item_count integer not null default 0,
  correct_count integer not null default 0,
  wrong_count integer not null default 0,
  score numeric(5,2),
  duration_seconds integer not null default 0,
  metadata jsonb not null default '{}'::jsonb
);

create table if not exists public.exam_attempts (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  exam_key text not null,
  exam_year integer,
  started_at timestamptz not null default now(),
  submitted_at timestamptz,
  score numeric(6,2),
  max_score numeric(6,2),
  correct_count integer not null default 0,
  wrong_count integer not null default 0,
  unanswered_count integer not null default 0,
  duration_seconds integer not null default 0,
  answers jsonb not null default '{}'::jsonb,
  weak_topics jsonb not null default '[]'::jsonb,
  metadata jsonb not null default '{}'::jsonb
);

create table if not exists public.daily_stats (
  user_id uuid not null references auth.users(id) on delete cascade,
  study_date date not null default current_date,
  reviews integer not null default 0,
  new_items integer not null default 0,
  correct_count integer not null default 0,
  wrong_count integer not null default 0,
  study_seconds integer not null default 0,
  exam_attempts integer not null default 0,
  best_exam_score numeric(6,2),
  primary key(user_id, study_date)
);

create index if not exists study_progress_user_due_idx on public.study_progress(user_id, due_at);
create index if not exists study_progress_user_topic_idx on public.study_progress(user_id, topic);
create index if not exists study_sessions_user_started_idx on public.study_sessions(user_id, started_at desc);
create index if not exists exam_attempts_user_started_idx on public.exam_attempts(user_id, started_at desc);

-- Mở rộng danh sách mode hợp lệ cho phiên học (bản trước thiếu 3 mode luyện đề mới:
-- word_formation, sentence_transform, translation, và thiếu 'cloze').
alter table public.study_sessions drop constraint if exists study_sessions_mode_check;
alter table public.study_sessions add constraint study_sessions_mode_check
  check (mode in ('vocabulary','word_family','collocation','cloze','mock_exam','review','word_formation','sentence_transform','translation'));

alter table public.profiles enable row level security;
alter table public.study_progress enable row level security;
alter table public.study_sessions enable row level security;
alter table public.exam_attempts enable row level security;
alter table public.daily_stats enable row level security;

-- ===================== RLS POLICIES =====================
-- Mỗi user chỉ đọc/ghi được đúng hàng của chính mình (auth.uid() = user_id).
-- drop policy if exists ... rồi create lại — an toàn để chạy nhiều lần.

drop policy if exists profiles_select_own on public.profiles;
create policy profiles_select_own on public.profiles for select using (auth.uid() = user_id);
drop policy if exists profiles_insert_own on public.profiles;
create policy profiles_insert_own on public.profiles for insert with check (auth.uid() = user_id);
drop policy if exists profiles_update_own on public.profiles;
create policy profiles_update_own on public.profiles for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists profiles_delete_own on public.profiles;
create policy profiles_delete_own on public.profiles for delete using (auth.uid() = user_id);

drop policy if exists study_progress_select_own on public.study_progress;
create policy study_progress_select_own on public.study_progress for select using (auth.uid() = user_id);
drop policy if exists study_progress_insert_own on public.study_progress;
create policy study_progress_insert_own on public.study_progress for insert with check (auth.uid() = user_id);
drop policy if exists study_progress_update_own on public.study_progress;
create policy study_progress_update_own on public.study_progress for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists study_progress_delete_own on public.study_progress;
create policy study_progress_delete_own on public.study_progress for delete using (auth.uid() = user_id);

drop policy if exists study_sessions_select_own on public.study_sessions;
create policy study_sessions_select_own on public.study_sessions for select using (auth.uid() = user_id);
drop policy if exists study_sessions_insert_own on public.study_sessions;
create policy study_sessions_insert_own on public.study_sessions for insert with check (auth.uid() = user_id);
drop policy if exists study_sessions_update_own on public.study_sessions;
create policy study_sessions_update_own on public.study_sessions for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists study_sessions_delete_own on public.study_sessions;
create policy study_sessions_delete_own on public.study_sessions for delete using (auth.uid() = user_id);

drop policy if exists exam_attempts_select_own on public.exam_attempts;
create policy exam_attempts_select_own on public.exam_attempts for select using (auth.uid() = user_id);
drop policy if exists exam_attempts_insert_own on public.exam_attempts;
create policy exam_attempts_insert_own on public.exam_attempts for insert with check (auth.uid() = user_id);
drop policy if exists exam_attempts_update_own on public.exam_attempts;
create policy exam_attempts_update_own on public.exam_attempts for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists exam_attempts_delete_own on public.exam_attempts;
create policy exam_attempts_delete_own on public.exam_attempts for delete using (auth.uid() = user_id);

drop policy if exists daily_stats_select_own on public.daily_stats;
create policy daily_stats_select_own on public.daily_stats for select using (auth.uid() = user_id);
drop policy if exists daily_stats_insert_own on public.daily_stats;
create policy daily_stats_insert_own on public.daily_stats for insert with check (auth.uid() = user_id);
drop policy if exists daily_stats_update_own on public.daily_stats;
create policy daily_stats_update_own on public.daily_stats for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists daily_stats_delete_own on public.daily_stats;
create policy daily_stats_delete_own on public.daily_stats for delete using (auth.uid() = user_id);

-- ===================== KIỂM TRA NHANH =====================
-- Sau khi chạy xong, câu này phải trả về đúng 5 dòng, mỗi bảng >=4 policy (select/insert/update/delete):
-- select tablename, count(*) from pg_policies where schemaname='public' group by tablename order by 1;

-- v4: học theo câu lưu trong study_progress với item_type='question' và item_key='sentence:<id>',
-- nên không cần đổi CHECK constraint hay migration dữ liệu.

-- ===================== V6 LEARNING ANALYTICS / MULTI-USER =====================
-- Các cột dưới đây là additive migration, an toàn khi chạy lại.
alter table public.profiles add column if not exists daily_minutes_goal integer not null default 30;
alter table public.profiles add column if not exists daily_new_items_goal integer not null default 15;
alter table public.profiles add column if not exists daily_reviews_goal integer not null default 30;
alter table public.profiles add column if not exists target_exam_date date;
alter table public.profiles add column if not exists timezone text;

alter table public.daily_stats add column if not exists updated_at timestamptz not null default now();
alter table public.study_sessions add column if not exists updated_at timestamptz not null default now();

create index if not exists daily_stats_user_date_desc_idx on public.daily_stats(user_id, study_date desc);

-- Server-side trigger để updated_at luôn đáng tin khi sau này có nhiều client/web user.
create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at before update on public.profiles for each row execute function public.set_updated_at();
drop trigger if exists daily_stats_set_updated_at on public.daily_stats;
create trigger daily_stats_set_updated_at before update on public.daily_stats for each row execute function public.set_updated_at();
drop trigger if exists study_sessions_set_updated_at on public.study_sessions;
create trigger study_sessions_set_updated_at before update on public.study_sessions for each row execute function public.set_updated_at();

-- =====================================================================
-- V7 — MULTI-USER WEB / PRODUCTION HARDENING
-- Toàn bộ khối này là additive, an toàn khi chạy lại nhiều lần.
-- =====================================================================

-- ---------- 7.1 profiles: bổ sung cột hồ sơ công khai tối thiểu ----------
alter table public.profiles add column if not exists avatar_hue smallint not null default 210;
alter table public.profiles add column if not exists locale text not null default 'vi';
alter table public.profiles add column if not exists onboarded_at timestamptz;
alter table public.profiles add column if not exists last_seen_at timestamptz;

alter table public.profiles drop constraint if exists profiles_display_name_len;
alter table public.profiles add constraint profiles_display_name_len
  check (display_name is null or char_length(display_name) between 1 and 60);
alter table public.profiles drop constraint if exists profiles_avatar_hue_range;
alter table public.profiles add constraint profiles_avatar_hue_range
  check (avatar_hue between 0 and 360);

-- ---------- 7.2 Tự tạo profile khi có user mới (BẮT BUỘC cho multi-user) ----------
-- Trước V7, hàng profiles chỉ sinh ra khi client chủ động upsert goals.
-- User đăng ký rồi bỏ đi giữa chừng sẽ không có profile => join hụt, admin không đếm được.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (user_id, display_name, avatar_hue)
  values (
    new.id,
    coalesce(
      nullif(new.raw_user_meta_data->>'display_name',''),
      nullif(new.raw_user_meta_data->>'full_name',''),
      nullif(new.raw_user_meta_data->>'name',''),
      split_part(coalesce(new.email,'hoc-vien'),'@',1)
    ),
    (abs(hashtext(new.id::text)) % 361)
  )
  on conflict (user_id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- Backfill cho user đã đăng ký trước khi có trigger.
insert into public.profiles (user_id, display_name, avatar_hue)
select u.id,
       coalesce(nullif(u.raw_user_meta_data->>'display_name',''), split_part(coalesce(u.email,'hoc-vien'),'@',1)),
       (abs(hashtext(u.id::text)) % 361)
from auth.users u
left join public.profiles p on p.user_id = u.id
where p.user_id is null;

-- ---------- 7.3 learning_events: log append-only, chống lost-update đa thiết bị ----------
-- daily_stats là counter tổng hợp: hai thiết bị cùng offline rồi cùng sync sẽ
-- ghi đè nhau và mất số liệu. Event log là nguồn sự thật; daily_stats chỉ là cache.
create table if not exists public.learning_events (
  event_id uuid primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  event_type text not null check (event_type in ('review','quiz_answer','drill_answer','exam_submit','session_start','session_end')),
  item_key text,
  item_type text,
  topic text,
  quality smallint check (quality is null or quality between 0 and 5),
  is_correct boolean,
  is_new_item boolean not null default false,
  duration_seconds integer not null default 0 check (duration_seconds >= 0),
  session_id uuid,
  occurred_at timestamptz not null default now(),
  event_date date not null default current_date,
  client_id text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists learning_events_user_date_idx on public.learning_events(user_id, event_date desc);
create index if not exists learning_events_user_time_idx on public.learning_events(user_id, occurred_at desc);
create index if not exists learning_events_user_item_idx on public.learning_events(user_id, item_type, item_key);

alter table public.learning_events enable row level security;

drop policy if exists learning_events_select_own on public.learning_events;
create policy learning_events_select_own on public.learning_events for select using (auth.uid() = user_id);
drop policy if exists learning_events_insert_own on public.learning_events;
create policy learning_events_insert_own on public.learning_events for insert with check (auth.uid() = user_id);
-- Cố ý KHÔNG có policy update/delete: log là append-only, kể cả chính chủ.

-- ---------- 7.4 user_roles: phân quyền admin không nới RLS bảng học tập ----------
create table if not exists public.user_roles (
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null check (role in ('admin','moderator','tester')),
  granted_at timestamptz not null default now(),
  primary key (user_id, role)
);
alter table public.user_roles enable row level security;

drop policy if exists user_roles_select_own on public.user_roles;
create policy user_roles_select_own on public.user_roles for select using (auth.uid() = user_id);
-- Cấp/thu quyền chỉ làm bằng service-role key ở dashboard, không mở cho client.

create or replace function public.has_role(check_role text)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists(select 1 from public.user_roles where user_id = auth.uid() and role = check_role);
$$;

-- ---------- 7.5 View tổng hợp server-side (RLS vẫn áp dụng nhờ security_invoker) ----------
drop view if exists public.v_user_daily;
create view public.v_user_daily
with (security_invoker = true) as
select
  user_id,
  event_date as study_date,
  count(*) filter (where event_type in ('review','quiz_answer','drill_answer'))::int as reviews,
  count(*) filter (where is_new_item)::int                                            as new_items,
  count(*) filter (where is_correct is true)::int                                     as correct_count,
  count(*) filter (where is_correct is false)::int                                    as wrong_count,
  coalesce(sum(duration_seconds),0)::int                                              as study_seconds,
  count(*) filter (where event_type = 'exam_submit')::int                             as exam_attempts,
  max(occurred_at)                                                                    as last_activity
from public.learning_events
group by user_id, event_date;

drop view if exists public.v_user_overview;
create view public.v_user_overview
with (security_invoker = true) as
select
  p.user_id,
  p.display_name,
  p.daily_minutes_goal,
  p.daily_reviews_goal,
  p.target_exam_date,
  (select count(*) from public.study_progress sp where sp.user_id = p.user_id)                                  as tracked_items,
  (select count(*) from public.study_progress sp where sp.user_id = p.user_id and sp.status = 'mastered')       as mastered_items,
  (select count(*) from public.study_progress sp where sp.user_id = p.user_id and sp.due_at <= now())           as due_items,
  (select count(*) from public.study_sessions ss where ss.user_id = p.user_id and ss.ended_at is not null)      as finished_sessions,
  (select max(le.occurred_at) from public.learning_events le where le.user_id = p.user_id)                      as last_activity
from public.profiles p;

-- ---------- 7.6 RPC: người dùng tự xoá tài khoản (GDPR / "quyền được quên") ----------
create or replace function public.delete_my_account()
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  uid uuid := auth.uid();
begin
  if uid is null then
    raise exception 'Chua dang nhap';
  end if;
  delete from public.learning_events where user_id = uid;
  delete from public.exam_attempts  where user_id = uid;
  delete from public.study_sessions where user_id = uid;
  delete from public.study_progress where user_id = uid;
  delete from public.daily_stats    where user_id = uid;
  delete from public.user_roles     where user_id = uid;
  delete from public.profiles       where user_id = uid;
  delete from auth.users            where id = uid;
end;
$$;

revoke all on function public.delete_my_account() from public, anon;
grant execute on function public.delete_my_account() to authenticated;

-- ---------- 7.7 RPC: dồn daily_stats từ event log (idempotent, chống double-count) ----------
create or replace function public.rebuild_daily_stats(days_back integer default 120)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  uid uuid := auth.uid();
  touched integer;
begin
  if uid is null then
    raise exception 'Chua dang nhap';
  end if;

  insert into public.daily_stats as d
    (user_id, study_date, reviews, new_items, correct_count, wrong_count, study_seconds, exam_attempts, updated_at)
  select v.user_id, v.study_date, v.reviews, v.new_items, v.correct_count, v.wrong_count, v.study_seconds, v.exam_attempts, now()
  from public.v_user_daily v
  where v.user_id = uid
    and v.study_date >= current_date - days_back
  on conflict (user_id, study_date) do update set
    reviews       = greatest(d.reviews,       excluded.reviews),
    new_items     = greatest(d.new_items,     excluded.new_items),
    correct_count = greatest(d.correct_count, excluded.correct_count),
    wrong_count   = greatest(d.wrong_count,   excluded.wrong_count),
    study_seconds = greatest(d.study_seconds, excluded.study_seconds),
    exam_attempts = greatest(d.exam_attempts, excluded.exam_attempts),
    updated_at    = now();

  get diagnostics touched = row_count;
  return touched;
end;
$$;

revoke all on function public.rebuild_daily_stats(integer) from public, anon;
grant execute on function public.rebuild_daily_stats(integer) to authenticated;

-- ---------- 7.8 exam_attempts: updated_at + trigger ----------
alter table public.exam_attempts add column if not exists updated_at timestamptz not null default now();
drop trigger if exists exam_attempts_set_updated_at on public.exam_attempts;
create trigger exam_attempts_set_updated_at before update on public.exam_attempts for each row execute function public.set_updated_at();

alter table public.study_progress drop constraint if exists study_progress_item_key_len;
alter table public.study_progress add constraint study_progress_item_key_len
  check (char_length(item_key) between 1 and 200);

-- ---------- 7.9 KIỂM TRA SAU KHI CHẠY ----------
-- 1) Đủ policy:            select tablename, count(*) from pg_policies where schemaname='public' group by 1 order by 1;
--    (learning_events chỉ có 2 policy: select + insert — đúng thiết kế append-only.)
-- 2) Trigger tạo profile:  select tgname from pg_trigger where tgrelid='auth.users'::regclass;
-- 3) View chạy được:       select * from public.v_user_overview;   -- phải chỉ ra đúng 1 hàng của chính mình
-- 4) Không rò dữ liệu:     đăng nhập bằng 2 tài khoản khác nhau, mỗi bên chỉ thấy hàng của mình.

-- =====================================================================
-- V8 — CHỐNG LẠM DỤNG, REALTIME, CORPUS CÓ PHIÊN BẢN
-- Additive, an toàn khi chạy lại.
-- =====================================================================

-- ---------- 8.1 Hạn mức ghi ----------
-- Trước V8, client insert thẳng vào learning_events. RLS chỉ kiểm tra "hàng này có
-- phải của bạn không", KHÔNG kiểm tra "bạn đã ghi bao nhiêu hàng". Một tài khoản
-- hợp lệ vẫn có thể bơm hàng triệu hàng và làm phình database.
-- V8 đóng insert trực tiếp lại, bắt mọi ghi phải đi qua RPC có đếm hạn mức.

create table if not exists public.usage_quota (
  user_id uuid not null references auth.users(id) on delete cascade,
  quota_date date not null default current_date,
  events_written integer not null default 0,
  rpc_calls integer not null default 0,
  updated_at timestamptz not null default now(),
  primary key (user_id, quota_date)
);
alter table public.usage_quota enable row level security;

drop policy if exists usage_quota_select_own on public.usage_quota;
create policy usage_quota_select_own on public.usage_quota for select using (auth.uid() = user_id);
-- Cố ý không có insert/update policy: chỉ hàm security definer bên dưới được ghi.

create index if not exists usage_quota_date_idx on public.usage_quota(quota_date);

-- Hạn mức/ngày. Người học chăm nhất cũng khó vượt 2.000 lượt ôn/ngày,
-- nên 5.000 vừa rộng rãi cho người thật vừa chặn được kịch bản bơm dữ liệu.
create or replace function public.quota_limit_events()
returns integer language sql immutable as $$ select 5000 $$;

-- ---------- 8.2 RPC ghi event có kiểm tra hạn mức ----------
create or replace function public.log_learning_events(events jsonb)
returns table(accepted integer, rejected integer, quota_used integer, quota_limit integer)
language plpgsql
security definer
set search_path = public
as $$
declare
  uid        uuid := auth.uid();
  lim        integer := public.quota_limit_events();
  used       integer;
  incoming   integer;
  room       integer;
  inserted   integer := 0;
begin
  if uid is null then
    raise exception 'Chua dang nhap' using errcode = '28000';
  end if;
  if jsonb_typeof(events) <> 'array' then
    raise exception 'events phai la mang JSON' using errcode = '22023';
  end if;

  incoming := jsonb_array_length(events);
  if incoming = 0 then
    return query select 0, 0, 0, lim;
    return;
  end if;
  -- Chặn payload quá lớn trong một lần gọi.
  if incoming > 500 then
    raise exception 'Toi da 500 event moi lan goi' using errcode = '22023';
  end if;

  insert into public.usage_quota (user_id, quota_date, events_written, rpc_calls)
  values (uid, current_date, 0, 1)
  on conflict (user_id, quota_date) do update
    set rpc_calls = public.usage_quota.rpc_calls + 1, updated_at = now();

  select events_written into used
  from public.usage_quota where user_id = uid and quota_date = current_date;

  room := greatest(0, lim - used);
  if room = 0 then
    return query select 0, incoming, used, lim;
    return;
  end if;

  with candidate as (
    select
      coalesce((e->>'event_id')::uuid, gen_random_uuid())          as event_id,
      e->>'event_type'                                              as event_type,
      nullif(left(coalesce(e->>'item_key',''), 200), '')            as item_key,
      nullif(e->>'item_type','')                                    as item_type,
      nullif(left(coalesce(e->>'topic',''), 120), '')               as topic,
      nullif(e->>'quality','')::smallint                            as quality,
      nullif(e->>'is_correct','')::boolean                          as is_correct,
      coalesce(nullif(e->>'is_new_item','')::boolean, false)        as is_new_item,
      -- Chặn số liệu vô lý: một lượt học không thể kéo dài quá 2 giờ.
      least(greatest(coalesce(nullif(e->>'duration_seconds','')::integer, 0), 0), 7200) as duration_seconds,
      nullif(e->>'session_id','')::uuid                             as session_id,
      coalesce(nullif(e->>'occurred_at','')::timestamptz, now())    as occurred_at,
      coalesce(nullif(e->>'event_date','')::date, current_date)     as event_date,
      nullif(left(coalesce(e->>'client_id',''), 64), '')            as client_id,
      coalesce(e->'metadata', '{}'::jsonb)                          as metadata,
      row_number() over ()                                          as rn
    from jsonb_array_elements(events) as e
  ),
  valid as (
    select * from candidate
    where rn <= room
      and event_type in ('review','quiz_answer','drill_answer','exam_submit','session_start','session_end')
      -- Không nhận event của tương lai hay quá 90 ngày trước: chống bịa lịch sử học.
      and occurred_at <= now() + interval '10 minutes'
      and occurred_at >= now() - interval '90 days'
  ),
  ins as (
    insert into public.learning_events
      (event_id, user_id, event_type, item_key, item_type, topic, quality, is_correct,
       is_new_item, duration_seconds, session_id, occurred_at, event_date, client_id, metadata)
    select event_id, uid, event_type, item_key, item_type, topic, quality, is_correct,
           is_new_item, duration_seconds, session_id, occurred_at, event_date, client_id, metadata
    from valid
    on conflict (event_id) do nothing
    returning 1
  )
  select count(*)::integer into inserted from ins;

  update public.usage_quota
     set events_written = events_written + inserted, updated_at = now()
   where user_id = uid and quota_date = current_date;

  return query select inserted, incoming - inserted, used + inserted, lim;
end;
$$;

revoke all on function public.log_learning_events(jsonb) from public, anon;
grant execute on function public.log_learning_events(jsonb) to authenticated;

-- Đóng đường insert trực tiếp: từ giờ chỉ RPC ở trên ghi được.
drop policy if exists learning_events_insert_own on public.learning_events;

-- ---------- 8.3 Realtime ----------
-- Chỉ phát study_progress và daily_stats. KHÔNG phát learning_events: nó là log
-- ghi liên tục, phát đi sẽ tạo bão message mà client không dùng đến.
do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
    begin execute 'alter publication supabase_realtime add table public.study_progress'; exception when duplicate_object then null; end;
    begin execute 'alter publication supabase_realtime add table public.daily_stats';    exception when duplicate_object then null; end;
    begin execute 'alter publication supabase_realtime add table public.profiles';       exception when duplicate_object then null; end;
  end if;
end $$;

-- Realtime lọc theo RLS, nhưng cần REPLICA IDENTITY để gửi kèm giá trị cũ khi UPDATE.
alter table public.study_progress replica identity full;
alter table public.daily_stats    replica identity full;

-- ---------- 8.4 Corpus có phiên bản ----------
-- Đưa nội dung học từ JSON tĩnh sang bảng, để sửa nội dung mà không phải deploy lại.
-- Đọc công khai (kể cả chưa đăng nhập); ghi chỉ bằng service-role hoặc admin.
create table if not exists public.content_packs (
  pack_id     text primary key,
  version     integer not null default 1,
  title       text not null,
  description text,
  item_count  integer not null default 0,
  checksum    text,
  is_active   boolean not null default true,
  published_at timestamptz,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create table if not exists public.content_items (
  id       bigint generated by default as identity primary key,
  pack_id  text not null references public.content_packs(pack_id) on delete cascade,
  item_key text not null,
  payload  jsonb not null,
  sort_order integer not null default 0,
  unique (pack_id, item_key)
);

create index if not exists content_items_pack_idx on public.content_items(pack_id, sort_order);

alter table public.content_packs enable row level security;
alter table public.content_items enable row level security;

-- Nội dung ôn thi là công khai: cho phép đọc cả khi chưa đăng nhập, nhưng chỉ pack đang bật.
drop policy if exists content_packs_read on public.content_packs;
create policy content_packs_read on public.content_packs for select
  to anon, authenticated using (is_active);

drop policy if exists content_items_read on public.content_items;
create policy content_items_read on public.content_items for select
  to anon, authenticated
  using (exists (select 1 from public.content_packs p where p.pack_id = content_items.pack_id and p.is_active));

-- Ghi nội dung: chỉ admin. Service-role bỏ qua RLS nên script nạp dữ liệu vẫn chạy được.
drop policy if exists content_packs_admin_write on public.content_packs;
create policy content_packs_admin_write on public.content_packs for all
  to authenticated using (public.has_role('admin')) with check (public.has_role('admin'));

drop policy if exists content_items_admin_write on public.content_items;
create policy content_items_admin_write on public.content_items for all
  to authenticated using (public.has_role('admin')) with check (public.has_role('admin'));

drop trigger if exists content_packs_set_updated_at on public.content_packs;
create trigger content_packs_set_updated_at before update on public.content_packs
  for each row execute function public.set_updated_at();

-- Client gọi hàm này trước để biết có cần tải lại nội dung không, thay vì tải mù cả gói.
create or replace function public.content_manifest()
returns table(pack_id text, version integer, title text, item_count integer, checksum text, published_at timestamptz)
language sql
stable
security definer
set search_path = public
as $$
  select pack_id, version, title, item_count, checksum, published_at
  from public.content_packs where is_active order by pack_id;
$$;

grant execute on function public.content_manifest() to anon, authenticated;

-- ---------- 8.5 KIỂM TRA ----------
-- learning_events phải KHÔNG còn policy insert (chỉ còn select):
--   select policyname, cmd from pg_policies where tablename='learning_events';
-- Thử vượt hạn mức:
--   select * from public.log_learning_events('[]'::jsonb);
-- Realtime đã bật:
--   select tablename from pg_publication_tables where pubname='supabase_realtime';

-- =====================================================================
-- V10 — CHỊU TẢI VÀ CHỐNG LẠM DỤNG PHÍA MÁY CHỦ
--
-- Điểm cần hiểu trước khi đọc phần này: đặt web tĩnh sau Cloudflare KHÔNG bảo vệ
-- Supabase. Trình duyệt gọi thẳng https://<ref>.supabase.co, traffic đó không đi
-- qua Cloudflare. Muốn có WAF/rate-limit ở tầng mạng cho API thì phải gắn custom
-- domain của Supabase vào Cloudflare (xem DEPLOYMENT.md). Khối SQL dưới đây là lớp
-- phòng thủ nằm trong chính database, luôn có hiệu lực bất kể đặt sau CDN nào.
-- =====================================================================

-- ---------- 10.1 Hạn mức cho các RPC tốn tài nguyên ----------
-- rebuild_daily_stats() quét toàn bộ learning_events của người dùng trong 120 ngày
-- rồi gộp nhóm. Client gọi nó ở mỗi lần đồng bộ. Trước V10 nó không có giới hạn nào:
-- một tài khoản hợp lệ gọi lặp trong vòng lặp là đủ làm nghẽn CPU của database.
alter table public.usage_quota add column if not exists heavy_rpc_calls integer not null default 0;
alter table public.usage_quota add column if not exists last_heavy_rpc timestamptz;

create or replace function public.quota_limit_heavy_rpc()
returns integer language sql immutable as $$ select 120 $$;   -- ~1 lần / 12 phút / ngày

-- Đếm và chặn. Trả về true nếu được phép chạy tiếp.
create or replace function public.consume_heavy_rpc(min_gap_seconds integer default 20)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  uid  uuid := auth.uid();
  used integer;
  last timestamptz;
begin
  if uid is null then
    raise exception 'Chua dang nhap' using errcode = '28000';
  end if;

  insert into public.usage_quota (user_id, quota_date, heavy_rpc_calls, last_heavy_rpc)
  values (uid, current_date, 0, null)
  on conflict (user_id, quota_date) do nothing;

  select heavy_rpc_calls, last_heavy_rpc into used, last
  from public.usage_quota where user_id = uid and quota_date = current_date
  for update;

  -- Chặn gọi dồn dập: hai lần liên tiếp phải cách nhau tối thiểu min_gap_seconds.
  if last is not null and last > now() - make_interval(secs => min_gap_seconds) then
    return false;
  end if;
  if used >= public.quota_limit_heavy_rpc() then
    return false;
  end if;

  update public.usage_quota
     set heavy_rpc_calls = heavy_rpc_calls + 1, last_heavy_rpc = now(), updated_at = now()
   where user_id = uid and quota_date = current_date;
  return true;
end;
$$;

revoke all on function public.consume_heavy_rpc(integer) from public, anon;
grant execute on function public.consume_heavy_rpc(integer) to authenticated;

-- Bọc hạn mức vào rebuild_daily_stats. Trả -1 nghĩa là bị từ chối vì hạn mức, KHÔNG
-- phải lỗi — client hiểu là "bỏ qua lần này", tiến trình vẫn nằm an toàn trên máy.
create or replace function public.rebuild_daily_stats(days_back integer default 120)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  uid uuid := auth.uid();
  touched integer;
begin
  if uid is null then
    raise exception 'Chua dang nhap' using errcode = '28000';
  end if;
  if not public.consume_heavy_rpc(20) then
    return -1;
  end if;
  -- Kẹp tham số: client không được tự ý yêu cầu quét 10 năm dữ liệu.
  days_back := least(greatest(coalesce(days_back, 120), 1), 400);

  insert into public.daily_stats as d
    (user_id, study_date, reviews, new_items, correct_count, wrong_count, study_seconds, exam_attempts, updated_at)
  select v.user_id, v.study_date, v.reviews, v.new_items, v.correct_count, v.wrong_count, v.study_seconds, v.exam_attempts, now()
  from public.v_user_daily v
  where v.user_id = uid and v.study_date >= current_date - days_back
  on conflict (user_id, study_date) do update set
    reviews       = greatest(d.reviews,       excluded.reviews),
    new_items     = greatest(d.new_items,     excluded.new_items),
    correct_count = greatest(d.correct_count, excluded.correct_count),
    wrong_count   = greatest(d.wrong_count,   excluded.wrong_count),
    study_seconds = greatest(d.study_seconds, excluded.study_seconds),
    exam_attempts = greatest(d.exam_attempts, excluded.exam_attempts),
    updated_at    = now();

  get diagnostics touched = row_count;
  return touched;
end;
$$;

revoke all on function public.rebuild_daily_stats(integer) from public, anon;
grant execute on function public.rebuild_daily_stats(integer) to authenticated;

-- ---------- 10.2 Đóng đường đọc corpus cho khách vô danh ----------
-- V8 mở content_items cho `anon` đọc với lý do "nội dung ôn thi là công khai". Điều
-- đó đúng về mặt nội dung nhưng sai về mặt chịu tải: khoá anon nằm công khai trong
-- mã nguồn, nên bất kỳ ai cũng kéo được toàn bộ corpus lặp vô hạn. Gói từ vựng nặng
-- ~1,7 MB — đây là bộ khuếch đại băng thông tính tiền trên hoá đơn Supabase.
--
-- Người học chưa đăng nhập vẫn dùng app bình thường: họ đọc JSON tĩnh đóng gói sẵn,
-- do CDN phục vụ (Cloudflare/Vercel hấp thụ được, và miễn phí). Chỉ phần NÂNG CẤP
-- nội dung từ database mới cần tài khoản.
drop policy if exists content_packs_read on public.content_packs;
create policy content_packs_read on public.content_packs for select
  to authenticated using (is_active);

drop policy if exists content_items_read on public.content_items;
create policy content_items_read on public.content_items for select
  to authenticated
  using (exists (select 1 from public.content_packs p
                 where p.pack_id = content_items.pack_id and p.is_active));

revoke execute on function public.content_manifest() from anon;
grant execute on function public.content_manifest() to authenticated;

-- ---------- 10.3 Chỉ số vận hành cho admin ----------
-- Không có bảng này thì không biết ai đang chạm trần, và một đợt lạm dụng chỉ lộ ra
-- khi hoá đơn về.
drop view if exists public.v_quota_usage;
create view public.v_quota_usage
with (security_invoker = true) as
select quota_date,
       count(*)                                             as active_users,
       sum(events_written)                                  as events_total,
       max(events_written)                                  as events_max_single_user,
       count(*) filter (where events_written >= public.quota_limit_events())      as users_at_event_cap,
       count(*) filter (where heavy_rpc_calls >= public.quota_limit_heavy_rpc())  as users_at_rpc_cap
from public.usage_quota
group by quota_date
order by quota_date desc;

-- Admin xem được toàn bộ hạn mức; người dùng thường vẫn chỉ thấy hàng của mình.
drop policy if exists usage_quota_admin_read on public.usage_quota;
create policy usage_quota_admin_read on public.usage_quota for select
  to authenticated using (public.has_role('admin'));

-- ---------- 10.4 KIỂM TRA ----------
-- Hạn mức RPC nặng có chặn gọi dồn:
--   select public.consume_heavy_rpc(20);  -- true
--   select public.consume_heavy_rpc(20);  -- false (chưa đủ 20 giây)
-- Khách vô danh không đọc được corpus:
--   đăng xuất rồi gọi content_manifest() → phải bị từ chối
-- Xem tình hình hạn mức:
--   select * from public.v_quota_usage limit 14;
